@baseUrl = http://localhost:23109/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFV0ZW50ZSI6IjZhMGRjZTgxMTA1OTY3ZTBhMjRjOTg1ZSIsInJ1b2xvQ2FzYSI6IklucXVpbGlubyIsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3Nzk3Mzc0OTEsImV4cCI6MTc4MDk0NzA5MX0.--9CiCaBo-R5BacWOK0hwQx_uINEGrtf-DziLAwzhiE
@idCasa = 6659f0b4e6a3c2f6a2d1a111
@idProblema = <id_problema>
@idUtente = 6a0dce81105967e0a24c985e

### Health
GET {{baseUrl}}/health

### Lista problemi
GET {{baseUrl}}/case/{{idCasa}}/problemi
Authorization: Bearer {{token}}

### Lista problemi non risolti
GET {{baseUrl}}/case/{{idCasa}}/problemi/non-risolti
Authorization: Bearer {{token}}

### Dettaglio problema
GET {{baseUrl}}/case/{{idCasa}}/problemi/{{idProblema}}
Authorization: Bearer {{token}}

### Segnala problema
POST {{baseUrl}}/case/{{idCasa}}/problemi
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nome": "Perdita in bagno",
  "descrizione": "Perdita dal rubinetto del lavandino",
  "priorita": "Media"
}

### Elimina problema
DELETE {{baseUrl}}/case/{{idCasa}}/problemi/{{idProblema}}
Authorization: Bearer {{token}}

### Auto-assegna problema (Inquilino)
PUT {{baseUrl}}/case/{{idCasa}}/problemi/{{idProblema}}/autoassegna
Authorization: Bearer {{token}}

### Assegna problema (HomeAdmin)
PUT {{baseUrl}}/case/{{idCasa}}/problemi/{{idProblema}}/assegna
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "idUtente": "{{idUtente}}"
}

### De-assegna problema (HomeAdmin)
PUT {{baseUrl}}/case/{{idCasa}}/problemi/{{idProblema}}/assegna
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "idUtente": null
}

### Aggiorna stato problema
PATCH {{baseUrl}}/case/{{idCasa}}/problemi/{{idProblema}}/stato
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "stato": "Risolto"
}

### Aggiorna priorita problema
PATCH {{baseUrl}}/case/{{idCasa}}/problemi/{{idProblema}}/priorita
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "priorita": "Urgente"
}

