services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT:-23109}
    image: coincasa:latest
    env_file:
      - .env
    ports:
      - "${PORT:-23109}:${PORT:-23109}"
    restart: unless-stopped

