sonar.projectKey=MarcelloPastore_Progetto_Ingegneria_del_Software
sonar.organization=marcellopastore
sonar.host.url=https://sonarcloud.io

sonar.exclusions=**/*.cpp,**/*.h,**/*.hpp,**/*.c,**/*.cc,**/linux/**,**/windows/**
# Escludo temporaneamente Dart perché il plugin SonarCloud è incompatibile con GitHub Actions
sonar.exclusions=**/*.dart,**/dart/**,**/lib/**,**/test/**
