sonar.projectKey=MarcelloPastore_Progetto_Ingegneria_del_Software
sonar.organization=marcellopastore
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

# Analyze TypeScript/JavaScript code
sonar.sources=src
sonar.tests=test

# Exclude specific languages and directories that shouldn't be analyzed
sonar.exclusions=**/*.dart,**/dart/**,**/lib/**,**/*.cpp,**/*.cc,**/*.c,**/*.h,**/*.hpp,**/linux/**,**/windows/**,**/node_modules/**,**/dist/**,**/build/**

# Coverage configuration
sonar.javascript.lcov.reportPaths=coverage/lcov.info
