sonar.projectKey=MarcelloPastore_Progetto_Ingegneria_del_Software
sonar.organization=marcellopastore
sonar.host.url=https://sonarcloud.io
sonar.sources=src,index.ts
sonar.tests=test
sonar.test.inclusions=test/**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/coincasa_app_flutter_frontend/**
